export const ROUTES = {
  HOME: '/',
  BLOG: '/static/doc/blog',
  DOWNLOADS: '/downloads',
  PRICING: '/pricing',
  DOCS: '/static/doc/docs/intro',
  O_NAS: '/static/doc/blog',
  NOTY_PRAWNE: '#',
  RODO: '#',
  IDENTYFIKACJA: '/identyfikacja',
  WISEVISION_LORA_BRIDGE: '/wisevision-lora-bridge',
  WIDEO_NA_ZYWO: '/wideo-na-zywo',
  ZARZADZANIE_WIDEO: '/data-management',
  ZDALNY_DOSTEP: '/zdalny-dostep',
  COVID: '/covid',
  TWITTER: '#',
  LINKEDIN: 'https://www.linkedin.com/company/wisevision-pl',
  POBIERZ_SPECYFIKACJA: 'static/files/dummy.pdf',
  DOWNLOAD_DOCUMENTATION: 'static/files/dummy.pdf',
  DOWNLOAD_RODO: 'static/files/dummy.pdf',
  DOWNLOAD_NOTES: 'static/files/dummy.pdf',
};
