export const ROUTES = {
  HOME: '/',
  BLOG: 'https://wisevision.tech/blog',
  DO_POBRANIA: '/do-pobrania',
  CENNIK: '/cennik',
  DOKUMENTACJA: 'https://wisevision.tech/docs/intro',
  O_NAS: 'https://wisevision.tech/blog/Witajcie',
  NOTY_PRAWNE: '#',
  RODO: '#',
  IDENTYFIKACJA: '/identyfikacja',
  ANALITYKA_DLA_HANDLU: '/analityka-dla-handlu',
  WIDEO_NA_ZYWO: '/wideo-na-zywo',
  ZARZADZANIE_WIDEO: '/zarzadzanie-wideo',
  ZDALNY_DOSTEP: '/zdalny-dostep',
  COVID: '/covid',
  TWITTER: '#',
  LINKEDIN: 'https://www.linkedin.com/company/wisevision-pl',
  POBIERZ_SPECYFIKACJA: 'static/files/dummy.pdf',
  POBIERZ_DOKUMENTACJA: 'static/files/dummy.pdf',
  POBIERZ_RODO: 'static/files/dummy.pdf',
  POBIERZ_NOTY: 'static/files/dummy.pdf',
};
