export const ROUTES = {
  HOME: '/',
  BLOG: '#',
  DOKUMENTACJA: '/dokumentacja',
  CENNIK: '/cennik',
  O_NAS: '#',
  NOTY_PRAWNE: '#',
  RODO: '#',
  IDENTYFIKACJA: '/identyfikacja',
  ANALITYKA_DLA_HANDLU: '/analityka-dla-handlu',
  WIDEO_NA_ZYWO: '/wideo-na-zywo',
  ZARZADZANIE_WIDEO: '/zarzadzanie-wideo',
  ZDALNY_DOSTEP: '/zdalny-dostep',
  COVID: '/covid',
  TWITTER: '#',
  LINKEDIN: '#',
  POBIERZ_SPECYFIKACJA: 'static/files/dummy.pdf',
  POBIERZ_DOKUMENTACJA: 'static/files/dummy.pdf',
  POBIERZ_RODO: 'static/files/dummy.pdf',
  POBIERZ_NOTY: 'static/files/dummy.pdf',
};
